{{- define "fdr-helper.configmap.tpl" -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "service.fullname" . }}
  labels:
{{ include "application.labels" . | indent 4 }}
data:
  APP_PORT: '{{ .Values.port | default 5000 }}'
  REFERENCE_API_URL: '{{ .Values.serviceReferenceUrl | default (printf "http://%s-fdr-service-reference:5000" .Release.Name) }}'
  VOUCHER_API_URL: '{{ .Values.serviceVoucherUrl | default (printf "http://%s-fdr-service-voucher:5000" .Release.Name) }}'
  RECEIPT_API_URL: '{{ .Values.serviceReceiptUrl | default (printf "http://%s-fdr-service-receipt:5000" .Release.Name) }}'
  DRAW_API_URL: '{{ .Values.serviceDrawUrl | default (printf "http://%s-fdr-service-draw:5000" .Release.Name) }}'
  SEED_DATA_SET: '{{ .Values.seedDataSet }}'
  AUTH_AUDIENCE: '{{ .Values.authAudience }}'
  AUTH_CLIENT_ID: '{{ .Values.authClientId }}'
  AUTH_LOG_LEVEL: '{{ .Values.authLogLevel }}'
  AUTH_TENANT: '{{ .Values.authTenant }}'


{{- end -}}
{{- define "fdr-helper.configmap" -}}
{{- include "fdr-helper.util.merge" (append . "fdr-helper.configmap.tpl") -}}
{{- end -}}