{{- define "fdr-helper.databaseJobsMigrate.tpl" -}}

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "application.fullname" . }}-db-migrate
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook-weight": "4"
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      initContainers:
        - name: wait-for-postgresql
          image: busybox
          command:
            - /bin/sh
            - -c
            - |
              echo checking connectivity to $PGHOST:$PGPORT
              until nc -z -w1 $PGHOST $PGPORT; do
                echo not ready
                sleep 2
              done
              echo ready
          env:
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  name: {{ include "application.fullname" . }}
                  key: host
            - name: PGPORT
              valueFrom:
                secretKeyRef:
                  name: {{ include "application.fullname" . }}
                  key: port
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default (printf "version-%s" .Chart.Version) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "application.fullname" . }}
          env:
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: {{ include "application.fullname" . }}
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "application.fullname" . }}
                  key: password
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  name: {{ include "application.fullname" . }}
                  key: host
            - name: PGPORT
              valueFrom:
                secretKeyRef:
                  name: {{ include "application.fullname" . }}
                  key: port
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ include "application.fullname" . }}
                  key: dbname
            - name: DB_URI
              value: ""
          command: ["npm", "run", "db:migrate"]
      restartPolicy: Never
  backoffLimit: 4


{{- end -}}
{{- define "fdr-helper.databaseJobsMigrate" -}}
{{- include "fdr-helper.util.merge" (append . "fdr-helper.databaseJobsMigrate.tpl") -}}
{{- end -}}