{{- define "fdr-helper.databaseSecret.tpl" -}}

{{ if .Values.dbSecretName }}
# Connection info for AWS-hosted DB from AWS Secrets Manager
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: {{ include "application.fullname" . }}
  labels:
{{ include "application.labels" . | indent 4 }}
spec:
  backendType: secretsManager
  # optional: specify role to assume when retrieving the data
  #roleArn: arn:aws:iam::123456789012:role/test-role
  dataFrom:
    - {{ .Values.dbSecretName }}
{{ else }}
# Connection info for kubernetes-hosted Postgres DB
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application.fullname" . }}
  labels:
{{ include "application.labels" . | indent 4 }}
type: Opaque
stringData:
  host: '{{ .Release.Name }}-db'
  username: '{{ index .Values "application-db" "postgresqlUsername" }}'
  password: '{{ index .Values "application-db" "postgresqlPassword" }}'
  port: '{{ index .Values "application-db" "port" }}'
  engine: 'postgres'
  dbname: '{{ index .Values "application-db" "postgresqlDatabase" }}'
{{- end }}

{{- end -}}
{{- define "fdr-helper.databaseSecret" -}}
{{- include "fdr-helper.util.merge" (append . "fdr-helper.databaseSecret.tpl") -}}
{{- end -}}