{{- define "fdr-helper.databaseJobsLoadSeedData.tpl" -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "application.fullname" . }}-db-seed
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook-weight": "5"
{{- if .Values.reloadSeedData }}
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
{{- else }}
    "helm.sh/hook": post-install
{{- end }}
spec:
  template:
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default (printf "version-%s" .Chart.Version) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "application.fullname" . }}
          env:
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: {{ include "application.fullname" . }}
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "application.fullname" . }}
                  key: password
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  name: {{ include "application.fullname" . }}
                  key: host
            - name: PGPORT
              valueFrom:
                secretKeyRef:
                  name: {{ include "application.fullname" . }}
                  key: port
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ include "application.fullname" . }}
                  key: dbname
            - name: DB_URI
              value: ""
          command: ["npm", "run", "db:seed"]
      restartPolicy: Never
  backoffLimit: 4
{{- end }}
{{- define "fdr-helper.databaseJobsLoadSeedData" -}}
{{- include "fdr-helper.util.merge" (append . "fdr-helper.databaseJobsLoadSeedData.tpl") -}}
{{- end -}}